AWSTemplateFormatVersion: 2010-09-09
Description: "S3 Bucket"

Parameters:
  s3bname:
    Description: Enter S3 bucket name
    Type: String

  InstanceTypeParam:
    Description: Select EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.large
    Description: Select instance type from list
    
Resources: 
  bucketNameC:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref s3bname
  
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5bf08bc8017c83b
      InstanceType: !Ref InstanceTypeParam
      Monitoring: true
      Tags:
        - Key: TestEC2
          Value: valueTestEC3


Outputs:
  BucketName:
    Value: !Ref 'bucketNameC'

